#!/bin/bash
set -e

# Update man pages
mandb -q || true

# Purge debconf
if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi

# Done
exit 0
