<Project Sdk="MSTest.Sdk/3.6.0">

  <PropertyGroup>
    <AssemblyName>Resitance.Core.Tests</AssemblyName>
    <RootNamespace>Tests</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
  </PropertyGroup>

  <PropertyGroup>
    <AnalysisLevel>none</AnalysisLevel>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Resistance.Core/Resistance.Core.csproj" />
  </ItemGroup>

</Project>
