<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>resistance.core</AssemblyName>
    <RootNamespace>ResiCalc</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <DebugType>embedded</DebugType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <NoWarn>CA2225</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Resistance.Core.Tests" />
  </ItemGroup>

</Project>
