<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>resistance</AssemblyName>
    <RootNamespace>ResiCalc</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Winexe</OutputType>
    <DebugType>embedded</DebugType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Resistance</Product>
    <Authors>Josip Medved</Authors>
    <Copyright>Copyright (c) 2025 Josip Medved</Copyright>
    <Company>www.medo64.com</Company>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationIcon>Assets/App.ico</ApplicationIcon>
    <ApplicationManifest>Properties/App.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Resistance.Core/Resistance.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>
</Project>
